#!/bin/bash

fps="${1:-10}" secs="${2:-10}" h="${3:-640}" w="${4:-480}"
alt="${5:-2}"

for (( i = 0; i < secs * fps; ++i )); do
  echo "tmp/$(( i % alt )).jpg"
  echo "$(( i * 1000000000 / fps ))"
done | LEIN_JAVA_CMD=java lein trampoline run tmp/out.webm $h $w $fps
